// Contenuti legali RestoHub (bozza da far validare da un avvocato/DPO).
// Provider: MOODD FOR WEB-DESIGN (impresa individuale, licenza E-Trader Dubai).
// Multilingua: 5 lingue admin. I link/URL restano relativi finché le pagine
// vivono nel motore; quando passeranno su restohub.cloud si cambiano gli URL.

export type LegalLang = "fr" | "en" | "it" | "nl" | "es";

export const LEGAL_LANGS: { code: LegalLang; label: string }[] = [
  { code: "fr", label: "FR" },
  { code: "en", label: "EN" },
  { code: "it", label: "IT" },
  { code: "nl", label: "NL" },
  { code: "es", label: "ES" },
];

// Dati identificativi del fornitore (dalla licenza di Dubai).
export const AZIENDA = {
  nome: "MOODD FOR WEB-DESIGN",
  prodotto: "RestoHub",
  titolare: "Vincenzo Santamaria",
  licenza: "E-Trader Professional License No. 1066221 — Dubai Department of Economy and Tourism",
  sede: "Dubai, United Arab Emirates",
  email: "admin@moodd.online",
};

export type LegalSection = { h: string; p: string };
export type LegalDocEntry = { title: string; updated: string; intro: string; sections: LegalSection[] };
export type LegalDoc = Record<LegalLang, LegalDocEntry>;

export const TERMS: LegalDoc = {
  fr: {
    title: "Conditions Générales d'Utilisation",
    updated: "Dernière mise à jour : août 2026",
    intro: "Les présentes conditions régissent l'utilisation de la plateforme RestoHub, éditée par MOODD FOR WEB-DESIGN (licence E-Trader n° 1066221, Dubai Department of Economy and Tourism, Émirats arabes unis). En créant un compte ou en utilisant RestoHub, vous acceptez ces conditions.",
    sections: [
      { h: "1. Éditeur", p: "RestoHub est édité et exploité par MOODD FOR WEB-DESIGN, entreprise individuelle immatriculée à Dubaï (Émirats arabes unis) sous la licence E-Trader n° 1066221, titulaire Vincenzo Santamaria. Contact : admin@moodd.online." },
      { h: "2. Objet", p: "RestoHub est une plateforme SaaS de gestion pour restaurants : réservations, commandes en ligne, menu, marketing et statistiques. Ces conditions encadrent la relation entre RestoHub et le professionnel (« le Client ») qui souscrit au service." },
      { h: "3. Compte et accès", p: "Le Client est responsable de l'exactitude des informations fournies, de la confidentialité de ses identifiants et de toute activité réalisée depuis son compte. Les accès sont réservés au personnel autorisé du Client." },
      { h: "4. Abonnement, prix et paiement", p: "L'accès se fait par abonnement. Les paiements sont traités de façon sécurisée via Stripe. Sauf mention contraire, l'abonnement se renouvelle automatiquement pour la même période. Les prix peuvent évoluer moyennant un préavis raisonnable." },
      { h: "5. Durée et résiliation", p: "Le Client peut résilier à tout moment ; la résiliation prend effet à la fin de la période en cours. RestoHub peut suspendre ou résilier l'accès en cas de manquement aux présentes conditions ou de non-paiement." },
      { h: "6. Obligations du Client", p: "Le Client s'engage à utiliser RestoHub de manière licite, à ne pas compromettre la sécurité du service et à respecter la réglementation applicable à son activité, notamment envers ses propres clients (informations, allergènes, protection des données)." },
      { h: "7. Disponibilité et support", p: "RestoHub met tout en œuvre pour un service fiable, sans garantir une disponibilité ininterrompue. Des interruptions peuvent survenir pour maintenance ou pour des causes indépendantes de notre volonté." },
      { h: "8. Données personnelles", p: "Le traitement des données est décrit dans notre Politique de confidentialité. Pour les données des clients finaux du restaurant, le Client agit comme responsable du traitement et RestoHub comme sous-traitant." },
      { h: "9. Propriété intellectuelle", p: "La plateforme RestoHub, sa marque et ses composants restent la propriété exclusive de MOODD FOR WEB-DESIGN. Le Client conserve la propriété de ses contenus et de ses données." },
      { h: "10. Responsabilité", p: "RestoHub ne saurait être tenu responsable des dommages indirects ou d'une perte de données imputable au Client. Dans la mesure permise par la loi, la responsabilité de RestoHub est limitée aux sommes versées au cours des douze derniers mois." },
      { h: "11. Modifications", p: "Ces conditions peuvent être mises à jour. Les modifications importantes seront communiquées ; la poursuite de l'utilisation vaut acceptation." },
      { h: "12. Droit applicable", p: "Les présentes conditions sont régies par les lois des Émirats arabes unis applicables dans l'Émirat de Dubaï, sous réserve des dispositions impératives protégeant le Client. Tout litige relève des tribunaux compétents de Dubaï." },
      { h: "13. Contact", p: "Pour toute question relative aux présentes conditions : admin@moodd.online." },
    ],
  },
  en: {
    title: "Terms & Conditions",
    updated: "Last updated: August 2026",
    intro: "These terms govern the use of the RestoHub platform, operated by MOODD FOR WEB-DESIGN (E-Trader License No. 1066221, Dubai Department of Economy and Tourism, United Arab Emirates). By creating an account or using RestoHub, you accept these terms.",
    sections: [
      { h: "1. Provider", p: "RestoHub is operated by MOODD FOR WEB-DESIGN, a sole establishment registered in Dubai (United Arab Emirates) under E-Trader License No. 1066221, owned by Vincenzo Santamaria. Contact: admin@moodd.online." },
      { h: "2. Purpose", p: "RestoHub is a SaaS management platform for restaurants: reservations, online ordering, menu, marketing and analytics. These terms govern the relationship between RestoHub and the professional (the « Client ») who subscribes to the service." },
      { h: "3. Account and access", p: "The Client is responsible for the accuracy of the information provided, for keeping credentials confidential, and for all activity carried out from its account. Access is reserved to the Client's authorised staff." },
      { h: "4. Subscription, pricing and payment", p: "Access is provided on a subscription basis. Payments are processed securely through Stripe. Unless stated otherwise, the subscription renews automatically for the same period. Prices may change with reasonable prior notice." },
      { h: "5. Term and termination", p: "The Client may cancel at any time; cancellation takes effect at the end of the current period. RestoHub may suspend or terminate access in the event of a breach of these terms or non-payment." },
      { h: "6. Client obligations", p: "The Client agrees to use RestoHub lawfully, not to compromise the security of the service, and to comply with the regulations applicable to its business, in particular towards its own customers (information, allergens, data protection)." },
      { h: "7. Availability and support", p: "RestoHub makes every effort to provide a reliable service but does not guarantee uninterrupted availability. Interruptions may occur for maintenance or for reasons beyond our control." },
      { h: "8. Personal data", p: "The processing of personal data is described in our Privacy Policy. For the restaurant's end-customer data, the Client acts as data controller and RestoHub as data processor." },
      { h: "9. Intellectual property", p: "The RestoHub platform, its brand and its components remain the exclusive property of MOODD FOR WEB-DESIGN. The Client retains ownership of its content and its data." },
      { h: "10. Liability", p: "RestoHub shall not be liable for indirect damages or for any loss of data attributable to the Client. To the extent permitted by law, RestoHub's liability is limited to the amounts paid during the last twelve months." },
      { h: "11. Changes", p: "These terms may be updated. Material changes will be communicated; continued use constitutes acceptance." },
      { h: "12. Governing law", p: "These terms are governed by the laws of the United Arab Emirates applicable in the Emirate of Dubai, subject to mandatory provisions protecting the Client. Any dispute falls under the competent courts of Dubai." },
      { h: "13. Contact", p: "For any question regarding these terms: admin@moodd.online." },
    ],
  },
  it: {
    title: "Termini e Condizioni",
    updated: "Ultimo aggiornamento: agosto 2026",
    intro: "I presenti termini regolano l'uso della piattaforma RestoHub, gestita da MOODD FOR WEB-DESIGN (licenza E-Trader n. 1066221, Dubai Department of Economy and Tourism, Emirati Arabi Uniti). Creando un account o utilizzando RestoHub, accetti questi termini.",
    sections: [
      { h: "1. Fornitore", p: "RestoHub è gestita da MOODD FOR WEB-DESIGN, impresa individuale registrata a Dubai (Emirati Arabi Uniti) con licenza E-Trader n. 1066221, titolare Vincenzo Santamaria. Contatto: admin@moodd.online." },
      { h: "2. Oggetto", p: "RestoHub è una piattaforma SaaS di gestione per ristoranti: prenotazioni, ordini online, menu, marketing e statistiche. Questi termini regolano il rapporto tra RestoHub e il professionista (« il Cliente ») che sottoscrive il servizio." },
      { h: "3. Account e accesso", p: "Il Cliente è responsabile della correttezza delle informazioni fornite, della riservatezza delle proprie credenziali e di ogni attività svolta dal proprio account. L'accesso è riservato al personale autorizzato del Cliente." },
      { h: "4. Abbonamento, prezzi e pagamento", p: "L'accesso avviene tramite abbonamento. I pagamenti sono gestiti in modo sicuro tramite Stripe. Salvo diversa indicazione, l'abbonamento si rinnova automaticamente per lo stesso periodo. I prezzi possono variare con ragionevole preavviso." },
      { h: "5. Durata e recesso", p: "Il Cliente può disdire in qualsiasi momento; la disdetta ha effetto al termine del periodo in corso. RestoHub può sospendere o chiudere l'accesso in caso di violazione dei termini o di mancato pagamento." },
      { h: "6. Obblighi del Cliente", p: "Il Cliente si impegna a usare RestoHub in modo lecito, a non compromettere la sicurezza del servizio e a rispettare le norme applicabili alla propria attività, in particolare verso i propri clienti (informazioni, allergeni, protezione dei dati)." },
      { h: "7. Disponibilità e supporto", p: "RestoHub si adopera per un servizio affidabile, senza garantire una disponibilità ininterrotta. Possono verificarsi interruzioni per manutenzione o per cause indipendenti dalla nostra volontà." },
      { h: "8. Dati personali", p: "Il trattamento dei dati è descritto nella nostra Informativa sulla privacy. Per i dati dei clienti finali del ristorante, il Cliente agisce come titolare del trattamento e RestoHub come responsabile del trattamento." },
      { h: "9. Proprietà intellettuale", p: "La piattaforma RestoHub, il suo marchio e i suoi componenti restano di proprietà esclusiva di MOODD FOR WEB-DESIGN. Il Cliente conserva la proprietà dei propri contenuti e dati." },
      { h: "10. Responsabilità", p: "RestoHub non è responsabile per danni indiretti o per la perdita di dati imputabile al Cliente. Nei limiti consentiti dalla legge, la responsabilità di RestoHub è limitata agli importi versati negli ultimi dodici mesi." },
      { h: "11. Modifiche", p: "I presenti termini possono essere aggiornati. Le modifiche rilevanti saranno comunicate; l'uso continuato costituisce accettazione." },
      { h: "12. Legge applicabile", p: "I presenti termini sono regolati dalle leggi degli Emirati Arabi Uniti applicabili nell'Emirato di Dubai, fatte salve le norme imperative a tutela del Cliente. Ogni controversia è devoluta ai tribunali competenti di Dubai." },
      { h: "13. Contatti", p: "Per qualsiasi domanda sui presenti termini: admin@moodd.online." },
    ],
  },
  nl: {
    title: "Algemene Voorwaarden",
    updated: "Laatst bijgewerkt: augustus 2026",
    intro: "Deze voorwaarden regelen het gebruik van het RestoHub-platform, beheerd door MOODD FOR WEB-DESIGN (E-Trader-licentie nr. 1066221, Dubai Department of Economy and Tourism, Verenigde Arabische Emiraten). Door een account aan te maken of RestoHub te gebruiken, aanvaardt u deze voorwaarden.",
    sections: [
      { h: "1. Aanbieder", p: "RestoHub wordt beheerd door MOODD FOR WEB-DESIGN, een eenmanszaak geregistreerd in Dubai (Verenigde Arabische Emiraten) onder E-Trader-licentie nr. 1066221, eigenaar Vincenzo Santamaria. Contact: admin@moodd.online." },
      { h: "2. Doel", p: "RestoHub is een SaaS-beheerplatform voor restaurants: reserveringen, online bestellen, menu, marketing en statistieken. Deze voorwaarden regelen de relatie tussen RestoHub en de professional (« de Klant ») die zich op de dienst abonneert." },
      { h: "3. Account en toegang", p: "De Klant is verantwoordelijk voor de juistheid van de verstrekte gegevens, de vertrouwelijkheid van zijn inloggegevens en alle activiteit vanaf zijn account. Toegang is voorbehouden aan bevoegd personeel van de Klant." },
      { h: "4. Abonnement, prijzen en betaling", p: "Toegang gebeurt via een abonnement. Betalingen worden veilig verwerkt via Stripe. Tenzij anders vermeld, wordt het abonnement automatisch verlengd voor dezelfde periode. Prijzen kunnen wijzigen met een redelijke kennisgeving vooraf." },
      { h: "5. Duur en opzegging", p: "De Klant kan op elk moment opzeggen; de opzegging gaat in aan het einde van de lopende periode. RestoHub kan de toegang opschorten of beëindigen bij schending van deze voorwaarden of niet-betaling." },
      { h: "6. Verplichtingen van de Klant", p: "De Klant verbindt zich ertoe RestoHub rechtmatig te gebruiken, de veiligheid van de dienst niet in gevaar te brengen en de op zijn activiteit toepasselijke regelgeving na te leven, met name jegens zijn eigen klanten (informatie, allergenen, gegevensbescherming)." },
      { h: "7. Beschikbaarheid en ondersteuning", p: "RestoHub streeft naar een betrouwbare dienst, maar garandeert geen ononderbroken beschikbaarheid. Onderbrekingen kunnen optreden voor onderhoud of door oorzaken buiten onze wil." },
      { h: "8. Persoonsgegevens", p: "De verwerking van gegevens wordt beschreven in ons Privacybeleid. Voor de gegevens van de eindklanten van het restaurant treedt de Klant op als verwerkingsverantwoordelijke en RestoHub als verwerker." },
      { h: "9. Intellectuele eigendom", p: "Het RestoHub-platform, het merk en de componenten blijven de exclusieve eigendom van MOODD FOR WEB-DESIGN. De Klant behoudt de eigendom van zijn inhoud en gegevens." },
      { h: "10. Aansprakelijkheid", p: "RestoHub is niet aansprakelijk voor indirecte schade of voor gegevensverlies dat aan de Klant te wijten is. Voor zover wettelijk toegestaan is de aansprakelijkheid van RestoHub beperkt tot de in de laatste twaalf maanden betaalde bedragen." },
      { h: "11. Wijzigingen", p: "Deze voorwaarden kunnen worden bijgewerkt. Belangrijke wijzigingen worden meegedeeld; voortgezet gebruik geldt als aanvaarding." },
      { h: "12. Toepasselijk recht", p: "Deze voorwaarden vallen onder het recht van de Verenigde Arabische Emiraten van toepassing in het Emiraat Dubai, onder voorbehoud van dwingende bepalingen ter bescherming van de Klant. Geschillen vallen onder de bevoegde rechtbanken van Dubai." },
      { h: "13. Contact", p: "Voor vragen over deze voorwaarden: admin@moodd.online." },
    ],
  },
  es: {
    title: "Términos y Condiciones",
    updated: "Última actualización: agosto de 2026",
    intro: "Los presentes términos regulan el uso de la plataforma RestoHub, gestionada por MOODD FOR WEB-DESIGN (licencia E-Trader n.º 1066221, Dubai Department of Economy and Tourism, Emiratos Árabes Unidos). Al crear una cuenta o utilizar RestoHub, aceptas estos términos.",
    sections: [
      { h: "1. Proveedor", p: "RestoHub está gestionada por MOODD FOR WEB-DESIGN, empresa individual registrada en Dubái (Emiratos Árabes Unidos) con licencia E-Trader n.º 1066221, titular Vincenzo Santamaria. Contacto: admin@moodd.online." },
      { h: "2. Objeto", p: "RestoHub es una plataforma SaaS de gestión para restaurantes: reservas, pedidos online, menú, marketing y estadísticas. Estos términos regulan la relación entre RestoHub y el profesional (« el Cliente ») que contrata el servicio." },
      { h: "3. Cuenta y acceso", p: "El Cliente es responsable de la exactitud de la información facilitada, de la confidencialidad de sus credenciales y de toda actividad realizada desde su cuenta. El acceso queda reservado al personal autorizado del Cliente." },
      { h: "4. Suscripción, precios y pago", p: "El acceso se realiza mediante suscripción. Los pagos se procesan de forma segura a través de Stripe. Salvo indicación en contrario, la suscripción se renueva automáticamente por el mismo período. Los precios pueden variar con un preaviso razonable." },
      { h: "5. Duración y cancelación", p: "El Cliente puede cancelar en cualquier momento; la cancelación surte efecto al final del período en curso. RestoHub puede suspender o cancelar el acceso en caso de incumplimiento de estos términos o de impago." },
      { h: "6. Obligaciones del Cliente", p: "El Cliente se compromete a usar RestoHub de forma lícita, a no comprometer la seguridad del servicio y a cumplir la normativa aplicable a su actividad, en particular frente a sus propios clientes (información, alérgenos, protección de datos)." },
      { h: "7. Disponibilidad y soporte", p: "RestoHub se esfuerza por ofrecer un servicio fiable, sin garantizar una disponibilidad ininterrumpida. Pueden producirse interrupciones por mantenimiento o por causas ajenas a nuestra voluntad." },
      { h: "8. Datos personales", p: "El tratamiento de datos se describe en nuestra Política de privacidad. Para los datos de los clientes finales del restaurante, el Cliente actúa como responsable del tratamiento y RestoHub como encargado del tratamiento." },
      { h: "9. Propiedad intelectual", p: "La plataforma RestoHub, su marca y sus componentes son propiedad exclusiva de MOODD FOR WEB-DESIGN. El Cliente conserva la propiedad de sus contenidos y datos." },
      { h: "10. Responsabilidad", p: "RestoHub no será responsable de daños indirectos ni de la pérdida de datos imputable al Cliente. En la medida permitida por la ley, la responsabilidad de RestoHub se limita a los importes abonados en los últimos doce meses." },
      { h: "11. Modificaciones", p: "Estos términos pueden actualizarse. Los cambios importantes se comunicarán; el uso continuado implica aceptación." },
      { h: "12. Ley aplicable", p: "Estos términos se rigen por las leyes de los Emiratos Árabes Unidos aplicables en el Emirato de Dubái, sin perjuicio de las disposiciones imperativas que protegen al Cliente. Cualquier disputa corresponde a los tribunales competentes de Dubái." },
      { h: "13. Contacto", p: "Para cualquier consulta sobre estos términos: admin@moodd.online." },
    ],
  },
};

export const PRIVACY: LegalDoc = {
  fr: {
    title: "Politique de Confidentialité",
    updated: "Dernière mise à jour : août 2026",
    intro: "La présente politique explique comment MOODD FOR WEB-DESIGN (« RestoHub ») traite les données personnelles dans le cadre de la plateforme RestoHub. Nous respectons le Règlement général sur la protection des données (RGPD) lorsqu'il s'applique aux données de personnes situées dans l'Union européenne.",
    sections: [
      { h: "1. Responsable du traitement", p: "RestoHub est édité par MOODD FOR WEB-DESIGN, Dubaï (Émirats arabes unis), licence E-Trader n° 1066221. Pour toute question relative aux données : admin@moodd.online." },
      { h: "2. Rôles (responsable / sous-traitant)", p: "Pour les données de compte du restaurateur et de son personnel, RestoHub agit comme responsable du traitement. Pour les données des clients finaux du restaurant (réservations, commandes), le restaurant est responsable du traitement et RestoHub agit comme sous-traitant, sur ses instructions." },
      { h: "3. Données collectées", p: "Selon l'usage : données de compte (nom, email, identifiants), données de réservation et de commande, contenus du restaurant (menu, photos), données de paiement (traitées par Stripe — nous ne stockons pas les numéros de carte) et données techniques (journaux, cookies, appareil)." },
      { h: "4. Finalités et bases légales", p: "Nous traitons les données pour fournir et sécuriser le service (exécution du contrat), gérer la facturation (obligation légale/contrat), améliorer la plateforme (intérêt légitime) et, le cas échéant, envoyer des communications (consentement)." },
      { h: "5. Sous-traitants", p: "Nous faisons appel à des prestataires de confiance : Supabase (base de données, authentification, hébergement), Stripe (paiements), Resend (emails transactionnels) et Hostinger (hébergement web). Chacun agit selon nos instructions et des garanties contractuelles." },
      { h: "6. Transferts internationaux", p: "Certaines données peuvent être traitées hors de l'Union européenne, y compris aux Émirats arabes unis. Des garanties appropriées sont mises en place lorsque la loi l'exige." },
      { h: "7. Durée de conservation", p: "Les données sont conservées le temps nécessaire aux finalités décrites, puis supprimées ou anonymisées, sauf obligation légale de conservation plus longue (par exemple en matière de facturation)." },
      { h: "8. Sécurité", p: "Nous mettons en œuvre des mesures techniques et organisationnelles pour protéger les données : accès chiffrés, contrôle des accès et sauvegardes. Aucun système n'est toutefois totalement infaillible." },
      { h: "9. Vos droits", p: "Vous disposez des droits d'accès, de rectification, d'effacement, de limitation, de portabilité et d'opposition. Pour les données de clients finaux d'un restaurant, adressez-vous d'abord au restaurant concerné (responsable du traitement)." },
      { h: "10. Cookies et stockage local", p: "RestoHub utilise des cookies et le stockage local strictement nécessaires au fonctionnement (session, préférences). Aucun traceur publicitaire tiers n'est utilisé dans l'espace d'administration." },
      { h: "11. Représentant dans l'UE", p: "En tant que responsable établi hors de l'UE proposant des services à des personnes dans l'UE, la désignation d'un représentant au sens de l'article 27 du RGPD est en cours d'évaluation ; ses coordonnées seront indiquées ici le cas échéant." },
      { h: "12. Réclamation", p: "Si vous estimez que vos droits ne sont pas respectés, vous pouvez introduire une réclamation auprès de l'autorité de protection des données compétente (en Belgique : l'Autorité de protection des données)." },
      { h: "13. Modifications", p: "Cette politique peut être mise à jour. La date de dernière mise à jour figure en haut de la page." },
      { h: "14. Contact", p: "Pour exercer vos droits ou pour toute question : admin@moodd.online." },
    ],
  },
  en: {
    title: "Privacy Policy",
    updated: "Last updated: August 2026",
    intro: "This policy explains how MOODD FOR WEB-DESIGN (« RestoHub ») processes personal data within the RestoHub platform. We comply with the General Data Protection Regulation (GDPR) where it applies to the data of individuals located in the European Union.",
    sections: [
      { h: "1. Data controller", p: "RestoHub is operated by MOODD FOR WEB-DESIGN, Dubai (United Arab Emirates), E-Trader License No. 1066221. For any question regarding data: admin@moodd.online." },
      { h: "2. Roles (controller / processor)", p: "For the restaurant owner's and staff's account data, RestoHub acts as data controller. For the restaurant's end-customer data (reservations, orders), the restaurant is the controller and RestoHub acts as processor, on its instructions." },
      { h: "3. Data we collect", p: "Depending on use: account data (name, email, credentials), reservation and order data, restaurant content (menu, photos), payment data (processed by Stripe — we do not store card numbers) and technical data (logs, cookies, device)." },
      { h: "4. Purposes and legal bases", p: "We process data to provide and secure the service (performance of the contract), manage billing (legal obligation/contract), improve the platform (legitimate interest) and, where applicable, send communications (consent)." },
      { h: "5. Sub-processors", p: "We rely on trusted providers: Supabase (database, authentication, hosting), Stripe (payments), Resend (transactional emails) and Hostinger (web hosting). Each acts on our instructions and under contractual safeguards." },
      { h: "6. International transfers", p: "Some data may be processed outside the European Union, including in the United Arab Emirates. Appropriate safeguards are put in place where required by law." },
      { h: "7. Retention", p: "Data is kept for as long as necessary for the purposes described, then deleted or anonymised, unless a longer legal retention obligation applies (for example, for billing)." },
      { h: "8. Security", p: "We implement technical and organisational measures to protect data: encrypted access, access control and backups. However, no system is entirely infallible." },
      { h: "9. Your rights", p: "You have the rights of access, rectification, erasure, restriction, portability and objection. For a restaurant's end-customer data, please contact the relevant restaurant first (the controller)." },
      { h: "10. Cookies and local storage", p: "RestoHub uses cookies and local storage strictly necessary for operation (session, preferences). No third-party advertising trackers are used in the administration area." },
      { h: "11. EU representative", p: "As a controller established outside the EU offering services to individuals in the EU, the appointment of a representative under Article 27 GDPR is being assessed; its details will be shown here if applicable." },
      { h: "12. Complaint", p: "If you believe your rights are not respected, you may lodge a complaint with the competent data protection authority (in Belgium: the Data Protection Authority)." },
      { h: "13. Changes", p: "This policy may be updated. The date of the last update is shown at the top of the page." },
      { h: "14. Contact", p: "To exercise your rights or for any question: admin@moodd.online." },
    ],
  },
  it: {
    title: "Informativa sulla Privacy",
    updated: "Ultimo aggiornamento: agosto 2026",
    intro: "La presente informativa spiega come MOODD FOR WEB-DESIGN (« RestoHub ») tratta i dati personali nell'ambito della piattaforma RestoHub. Rispettiamo il Regolamento generale sulla protezione dei dati (GDPR) quando si applica ai dati di persone che si trovano nell'Unione europea.",
    sections: [
      { h: "1. Titolare del trattamento", p: "RestoHub è gestita da MOODD FOR WEB-DESIGN, Dubai (Emirati Arabi Uniti), licenza E-Trader n. 1066221. Per qualsiasi domanda sui dati: admin@moodd.online." },
      { h: "2. Ruoli (titolare / responsabile)", p: "Per i dati dell'account del ristoratore e del suo personale, RestoHub agisce come titolare del trattamento. Per i dati dei clienti finali del ristorante (prenotazioni, ordini), il ristorante è titolare e RestoHub agisce come responsabile del trattamento, su sue istruzioni." },
      { h: "3. Dati raccolti", p: "A seconda dell'uso: dati dell'account (nome, email, credenziali), dati di prenotazione e ordine, contenuti del ristorante (menu, foto), dati di pagamento (gestiti da Stripe — non conserviamo i numeri di carta) e dati tecnici (log, cookie, dispositivo)." },
      { h: "4. Finalità e basi giuridiche", p: "Trattiamo i dati per fornire e mettere in sicurezza il servizio (esecuzione del contratto), gestire la fatturazione (obbligo legale/contratto), migliorare la piattaforma (legittimo interesse) e, se del caso, inviare comunicazioni (consenso)." },
      { h: "5. Responsabili del trattamento", p: "Ci avvaliamo di fornitori affidabili: Supabase (database, autenticazione, hosting), Stripe (pagamenti), Resend (email transazionali) e Hostinger (hosting web). Ciascuno agisce secondo le nostre istruzioni e garanzie contrattuali." },
      { h: "6. Trasferimenti internazionali", p: "Alcuni dati possono essere trattati fuori dall'Unione europea, inclusi gli Emirati Arabi Uniti. Ove richiesto dalla legge vengono adottate garanzie adeguate." },
      { h: "7. Conservazione", p: "I dati sono conservati per il tempo necessario alle finalità descritte, poi cancellati o anonimizzati, salvo obblighi legali di conservazione più lunghi (ad esempio per la fatturazione)." },
      { h: "8. Sicurezza", p: "Adottiamo misure tecniche e organizzative per proteggere i dati: accessi cifrati, controllo degli accessi e backup. Nessun sistema è però totalmente infallibile." },
      { h: "9. I tuoi diritti", p: "Hai diritto di accesso, rettifica, cancellazione, limitazione, portabilità e opposizione. Per i dati dei clienti finali di un ristorante, rivolgiti prima al ristorante interessato (titolare del trattamento)." },
      { h: "10. Cookie e archiviazione locale", p: "RestoHub usa cookie e archiviazione locale strettamente necessari al funzionamento (sessione, preferenze). Nessun tracciatore pubblicitario di terze parti è usato nell'area di amministrazione." },
      { h: "11. Rappresentante nell'UE", p: "In quanto titolare stabilito fuori dall'UE che offre servizi a persone nell'UE, la nomina di un rappresentante ai sensi dell'articolo 27 del GDPR è in fase di valutazione; i relativi recapiti saranno indicati qui se applicabile." },
      { h: "12. Reclamo", p: "Se ritieni che i tuoi diritti non siano rispettati, puoi presentare reclamo all'autorità di protezione dei dati competente (in Belgio: l'Autorità per la protezione dei dati)." },
      { h: "13. Modifiche", p: "La presente informativa può essere aggiornata. La data dell'ultimo aggiornamento è indicata in alto nella pagina." },
      { h: "14. Contatti", p: "Per esercitare i tuoi diritti o per qualsiasi domanda: admin@moodd.online." },
    ],
  },
  nl: {
    title: "Privacybeleid",
    updated: "Laatst bijgewerkt: augustus 2026",
    intro: "Dit beleid legt uit hoe MOODD FOR WEB-DESIGN (« RestoHub ») persoonsgegevens verwerkt binnen het RestoHub-platform. Wij leven de Algemene Verordening Gegevensbescherming (AVG/GDPR) na wanneer deze van toepassing is op gegevens van personen in de Europese Unie.",
    sections: [
      { h: "1. Verwerkingsverantwoordelijke", p: "RestoHub wordt beheerd door MOODD FOR WEB-DESIGN, Dubai (Verenigde Arabische Emiraten), E-Trader-licentie nr. 1066221. Voor vragen over gegevens: admin@moodd.online." },
      { h: "2. Rollen (verantwoordelijke / verwerker)", p: "Voor de accountgegevens van de restauranthouder en zijn personeel treedt RestoHub op als verwerkingsverantwoordelijke. Voor de gegevens van de eindklanten van het restaurant (reserveringen, bestellingen) is het restaurant de verantwoordelijke en treedt RestoHub op als verwerker, volgens zijn instructies." },
      { h: "3. Verzamelde gegevens", p: "Afhankelijk van het gebruik: accountgegevens (naam, e-mail, inloggegevens), reserverings- en bestelgegevens, restaurantinhoud (menu, foto's), betaalgegevens (verwerkt door Stripe — wij bewaren geen kaartnummers) en technische gegevens (logs, cookies, apparaat)." },
      { h: "4. Doeleinden en rechtsgronden", p: "Wij verwerken gegevens om de dienst te leveren en te beveiligen (uitvoering van de overeenkomst), facturatie te beheren (wettelijke verplichting/overeenkomst), het platform te verbeteren (gerechtvaardigd belang) en, indien van toepassing, communicatie te versturen (toestemming)." },
      { h: "5. Verwerkers", p: "Wij doen een beroep op betrouwbare aanbieders: Supabase (database, authenticatie, hosting), Stripe (betalingen), Resend (transactie-e-mails) en Hostinger (webhosting). Elk handelt volgens onze instructies en contractuele waarborgen." },
      { h: "6. Internationale doorgiften", p: "Sommige gegevens kunnen buiten de Europese Unie worden verwerkt, waaronder in de Verenigde Arabische Emiraten. Waar de wet dit vereist, worden passende waarborgen getroffen." },
      { h: "7. Bewaring", p: "Gegevens worden bewaard zolang als nodig voor de beschreven doeleinden en daarna verwijderd of geanonimiseerd, tenzij een langere wettelijke bewaarplicht geldt (bijvoorbeeld voor facturatie)." },
      { h: "8. Beveiliging", p: "Wij nemen technische en organisatorische maatregelen om gegevens te beschermen: versleutelde toegang, toegangscontrole en back-ups. Geen enkel systeem is echter volledig onfeilbaar." },
      { h: "9. Uw rechten", p: "U hebt recht op inzage, rectificatie, wissing, beperking, overdraagbaarheid en bezwaar. Voor de gegevens van eindklanten van een restaurant richt u zich eerst tot het betrokken restaurant (de verantwoordelijke)." },
      { h: "10. Cookies en lokale opslag", p: "RestoHub gebruikt cookies en lokale opslag die strikt noodzakelijk zijn voor de werking (sessie, voorkeuren). In de beheeromgeving worden geen advertentietrackers van derden gebruikt." },
      { h: "11. Vertegenwoordiger in de EU", p: "Als buiten de EU gevestigde verantwoordelijke die diensten aanbiedt aan personen in de EU, wordt de aanwijzing van een vertegenwoordiger in de zin van artikel 27 AVG beoordeeld; de gegevens worden hier vermeld indien van toepassing." },
      { h: "12. Klacht", p: "Als u meent dat uw rechten niet worden gerespecteerd, kunt u een klacht indienen bij de bevoegde gegevensbeschermingsautoriteit (in België: de Gegevensbeschermingsautoriteit)." },
      { h: "13. Wijzigingen", p: "Dit beleid kan worden bijgewerkt. De datum van de laatste bijwerking staat bovenaan de pagina." },
      { h: "14. Contact", p: "Om uw rechten uit te oefenen of voor vragen: admin@moodd.online." },
    ],
  },
  es: {
    title: "Política de Privacidad",
    updated: "Última actualización: agosto de 2026",
    intro: "Esta política explica cómo MOODD FOR WEB-DESIGN (« RestoHub ») trata los datos personales en el marco de la plataforma RestoHub. Cumplimos el Reglamento General de Protección de Datos (RGPD) cuando se aplica a los datos de personas situadas en la Unión Europea.",
    sections: [
      { h: "1. Responsable del tratamiento", p: "RestoHub está gestionada por MOODD FOR WEB-DESIGN, Dubái (Emiratos Árabes Unidos), licencia E-Trader n.º 1066221. Para cualquier consulta sobre datos: admin@moodd.online." },
      { h: "2. Roles (responsable / encargado)", p: "Para los datos de la cuenta del restaurador y su personal, RestoHub actúa como responsable del tratamiento. Para los datos de los clientes finales del restaurante (reservas, pedidos), el restaurante es el responsable y RestoHub actúa como encargado del tratamiento, siguiendo sus instrucciones." },
      { h: "3. Datos que recopilamos", p: "Según el uso: datos de cuenta (nombre, correo, credenciales), datos de reserva y pedido, contenidos del restaurante (menú, fotos), datos de pago (procesados por Stripe — no almacenamos números de tarjeta) y datos técnicos (registros, cookies, dispositivo)." },
      { h: "4. Finalidades y bases jurídicas", p: "Tratamos los datos para prestar y proteger el servicio (ejecución del contrato), gestionar la facturación (obligación legal/contrato), mejorar la plataforma (interés legítimo) y, en su caso, enviar comunicaciones (consentimiento)." },
      { h: "5. Encargados del tratamiento", p: "Recurrimos a proveedores de confianza: Supabase (base de datos, autenticación, alojamiento), Stripe (pagos), Resend (correos transaccionales) y Hostinger (alojamiento web). Cada uno actúa según nuestras instrucciones y garantías contractuales." },
      { h: "6. Transferencias internacionales", p: "Algunos datos pueden tratarse fuera de la Unión Europea, incluidos los Emiratos Árabes Unidos. Cuando la ley lo exige, se aplican garantías adecuadas." },
      { h: "7. Conservación", p: "Los datos se conservan el tiempo necesario para las finalidades descritas y luego se eliminan o anonimizan, salvo una obligación legal de conservación más larga (por ejemplo, para la facturación)." },
      { h: "8. Seguridad", p: "Aplicamos medidas técnicas y organizativas para proteger los datos: accesos cifrados, control de accesos y copias de seguridad. Sin embargo, ningún sistema es totalmente infalible." },
      { h: "9. Tus derechos", p: "Tienes derecho de acceso, rectificación, supresión, limitación, portabilidad y oposición. Para los datos de clientes finales de un restaurante, dirígete primero al restaurante correspondiente (el responsable)." },
      { h: "10. Cookies y almacenamiento local", p: "RestoHub utiliza cookies y almacenamiento local estrictamente necesarios para el funcionamiento (sesión, preferencias). No se usan rastreadores publicitarios de terceros en el área de administración." },
      { h: "11. Representante en la UE", p: "Como responsable establecido fuera de la UE que ofrece servicios a personas en la UE, se está evaluando la designación de un representante conforme al artículo 27 del RGPD; sus datos se indicarán aquí si procede." },
      { h: "12. Reclamación", p: "Si consideras que tus derechos no se respetan, puedes presentar una reclamación ante la autoridad de protección de datos competente (en Bélgica: la Autoridad de Protección de Datos)." },
      { h: "13. Modificaciones", p: "Esta política puede actualizarse. La fecha de la última actualización figura en la parte superior de la página." },
      { h: "14. Contacto", p: "Para ejercer tus derechos o para cualquier consulta: admin@moodd.online." },
    ],
  },
};
